### ISSUE TITLE
SearchOperators hidden popup

### ISSUE THREAD

**Issue by demonslord** [tonytomov/jqGrid#472]
Hi Tony,
There are a small issue with popup.
It doesn't have css property "z-index", so if parent element of jqgrid has z-index specified, this popup doesn't appear.

It can be fixed by 2 ways:
-  add style "z-index:99999;" at this line:
```javascript
var str = '<ul id="sopt_menu" class="ui-search-menu" role="menu" tabindex="0" style="z-index:99999;font-size:'+fs+';left:'+left+'px;top:'+top+'px;">',
```

- Or add "z-index:99999;" at .ui-search-menu class in ui.jqgrid.css
```css
.ui-search-menu { position: absolute; padding: 2px 5px; z-index:99999;}
```
Best Regards,
Alexander Bulei
